name: Build and publish Docker image

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GIT_COMMIT_HASH=${{ github.sha }}
            GIT_REPO_URL="https://github.com/${{ github.repository }}"

      - name: Restart server with latest image
        run: |
          ssh -o StrictHostKeyChecking=no flairsite@flair.r-anime.moe /bin/bash << 'EOF'
            # Causes this script to exit early and report a failure if any command errors
            set -e
          
            # Checkout latest changes from our repo, overwriting any local changes
            cd "/srv"
          
            # pull latest image
            docker pull ${{ steps.meta.outputs.tags }}
          
            # Restart the service to make the new stuff go live
            docker compose up -d seasonal_comment_face_survey
          EOF